name: QA
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  spotless:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Run Spotless
        run: mvn spotless:check
